name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u codetriad03 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t codetriad03/ca3:latest .
          docker push codetriad03/ca3:latest
